spring.application.name=wrapper

spring.datasource.url = https://gateway.marvel.com/v1/public/comics
spring.datasource.PublicKey = 23bcbeb0ba49ee64a339eae3329ad658
spring.datasource.PrivateKey = 16d2a0d1717b7b50c601570e495512d7d9474508
